<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/online/([\\.\\-0-9a-zA-Z]+)(/?)([^/]*)#",
		"RULE" => "alias=\$1",
		"ID" => "",
		"PATH" => "/desktop_app/router.php",
	),
	array(
		"CONDITION" => "#^/personal/favorite/([0-9]+)/#",
		"RULE" => "id=\$1&",
		"ID" => "ul:personal.favorite.detail",
		"PATH" => "/personal/favorite/detail.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/mob_app/([a-zA-Z0-9_-]+)/#",
		"RULE" => "page=\$1&",
		"ID" => "bitrix:mobileapp.demoapi",
		"PATH" => "/mob_app/index.php",
	),
	array(
		"CONDITION" => "#^/bitrix/services/ymarket/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/bitrix/services/ymarket/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/docs/([a-zA-Z0-9_-]+)/#",
		"RULE" => "ELEMENT_ID=\$1&",
		"ID" => "ab:react.doc",
		"PATH" => "/docs/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/online/(/?)([^/]*)#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/desktop_app/router.php",
	),
	array(
		"CONDITION" => "#^/stssync/calendar/#",
		"RULE" => "",
		"ID" => "bitrix:stssync.server",
		"PATH" => "/bitrix/services/stssync/calendar/index.php",
	),
	array(
		"CONDITION" => "/admin/components",
		"RULE" => "",
		"ID" => "digitalwand.admin_helper",
		"PATH" => "DigitalWand\\AdminHelper\\ComponentCreator",
	),
	array(
		"CONDITION" => "/personal/address",
		"RULE" => "",
		"ID" => "ul:address.list",
		"PATH" => "\\UL\\Main\\Personal\\AddressList",
		"SORT" => "100550",
	),
	array(
		"CONDITION" => "#^/actions/(.*)#",
		"RULE" => "data=\$1&",
		"ID" => "rest",
		"PATH" => "/local/route/ajax/service.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/service/(.*)#",
		"PATH" => "/local/route/ajax/ajax.php",
		"RULE" => "type=\$1&action=\$2&data=\$3",
		"ID" => "ajax",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/rest/forms/#",
		"RULE" => "",
		"ID" => "ab:feedback.form",
		"PATH" => "/local/components/ab/feedback.form/ajax.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "/search/result",
		"RULE" => "",
		"ID" => "ab:search.form",
		"PATH" => "\\AB\\SearchComponent",
		"SORT" => "100550",
	),
	array(
		"CONDITION" => "#^/rest2/(.*)#",
		"RULE" => "",
		"ID" => "restModule",
		"PATH" => "/rest/router.php",
		"SORT" => "1",
	),
	array(
		"CONDITION" => "/admin/remain",
		"RULE" => "",
		"ID" => "ul.main",
		"PATH" => "\\UL\\Main\\Import\\Prices\\AjaxHandler",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/rest/(.*)#",
		"RULE" => "data=\$1",
		"ID" => "restModule",
		"PATH" => "/rest/index.php",
		"SORT" => "100500",
	),
	array(
		"CONDITION" => "#^/catalog/#",
		"RULE" => "",
		"ID" => "ul:catalog.products",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/store/#",
		"RULE" => "",
		"ID" => "bitrix:catalog.store",
		"PATH" => "/store/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/shop/#",
		"RULE" => "",
		"ID" => "ul:shop.catalog",
		"PATH" => "/shop/index.php",
	),
	array(
		"CONDITION" => "#^/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/news/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/delivery/v1/dist/#",
		"RULE" => "",
		"ID" => "mig:mobile.delivery",
		"PATH" => "/delivery/v1/dist/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "/order",
		"RULE" => "",
		"ID" => "ul:order.creator",
		"PATH" => "\\UL\\Main\\OrderComponent",
	),
	array(
		"CONDITION" => "/help",
		"RULE" => "",
		"ID" => "ul:help",
		"PATH" => "\\UL\\Main\\Help\\HelpComponent",
		"SORT" => "100550",
	),
	array(
		"CONDITION" => "/da/",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/da/index.php",
		"SORT" => "100550",
	),
	array(
		"CONDITION" => "#^/lk/(.*)#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/lk/index.php",
		"SORT" => "200500",
	),
	array(
		"CONDITION" => "#^/delivery/v1/dist/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/delivery/v1/dist/index.php",
	),
	array(
		"CONDITION" => "#^/delivery/admin/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/delivery/admin/index.php",
	),
);

?>
