<?php
/**
 * Created by PhpStorm.
 * User: dremin_s
 * Date: 03.09.2016
 * Time: 14:41
 */

namespace UL\Main\Import;

use Exception;

class ImportException extends Exception
{
	/**
	 * ImportException constructor.
	 *
	 * @param string $message
	 * @param int $code
	 * @param Exception $previous
	 */
	public function __construct($message, $code = 0, Exception $previous = null)
	{
		parent::__construct($message, $code, $previous);
	}

	/**
	 * @method __toString
	 */
	public function __toString()
	{
		parent::__toString(); // TODO: Change the autogenerated stub
	}

}