#!/usr/bin/php
<?php
$_SERVER["DOCUMENT_ROOT"] = realpath(dirname(__FILE__)).'/../../..';
$root = $_SERVER["DOCUMENT_ROOT"];

define("NO_KEEP_STATISTIC", true);
define("NOT_CHECK_PERMISSIONS",true);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include.php");

use Bitrix\Main\Loader;

Loader::includeModule('grandmaster.console');

passthru('clear');

$Builder = new GrandMaster\Console\Builder();
$Builder->setScripts([

]);